version: '3'
services:
  download:
    build: download
    container_name: youtube-dl
    volumes:
      - .:/application
  crt:
    build: crt
    container_name: crt
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - .:/application
  serve:
    build: serve
    environment:
      - FLASK_ENV=development
    ports:
      - "80:80"  
    volumes:
      - .:/application
