version: '3'
services:
  download:
    build: ./download/
    container_name: youtube-dl
    volumes:
      - /home/frank/development/advent-of-code-2023:/application
      - /var/run/docker.sock:/var/run/docker.sock
  crt:
    build: ./crt/
    container_name: crt
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /home/frank/development/advent-of-code-2023:/application
      - /var/run/docker.sock:/var/run/docker.sock
  serve:
    build: ./serve/
    environment:
      - FLASK_ENV=development
    ports:
      - "80:80"  
    volumes:
      - /home/frank/development/advent-of-code-2023:/application
