version: '3'
services:
  download:
    depends_on:
      - redis
    build: download
    container_name: youtube-dl
    volumes:
      - .:/application
  crt:
    build: crt
    container_name: crt
    depends_on:
      - redis
    #devices:
      #- /dev/dri:/dev/dri
    volumes:
      - .:/application
  serve:
    build: serve
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
    #ports:
      #- "80:80"  
    volumes:
      - .:/application
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  web:
    build: web
    ports:
      - "3001:3000"
    volumes:
      - .:/application
    entrypoint: ["npx", "next", "dev"]
  haproxy:
    depends_on:
      - web
      - serve
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "80:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro