version: '3'
services:
  download:
    depends_on:
      - redis
    build: download
    container_name: youtube-dl
    volumes:
      - .:/application
  crt:
    build: crt
    container_name: crt
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - .:/application
  serve:
    build: serve
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
    ports:
      - "80:80"  
    volumes:
      - .:/application
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
