version: '3'
services:
  download:
    build: ./download/
    container_name: youtube-dl
    #command: /bin/bash
    #stdin_open: true
    #tty: true
    volumes:
      - .:/application
      - /var/run/docker.sock:/var/run/docker.sock
  crt:
    build: ./crt/
    container_name: crt
    #stdin_open: true
    #tty: true
    #devices:
      #- /dev/dri:/dev/dri
    volumes:
      - .:/application
      - /var/run/docker.sock:/var/run/docker.sock
  serve:
    build: ./serve/
    environment:
      - FLASK_ENV=development
    ports:
      - "80:80"  
    volumes:
      - .:/application
