version: '3.7'  # Updated version to support newer features
services:
  download:
    image: frankinaustin/television-download:latest
    deploy:
      replicas: 2
    volumes:
      - .:/application
  crt:
    image: frankinaustin/television-crt:latest
    volumes:
      - .:/application
    deploy:
      replicas: 6
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  nextjs:
    image: frankinaustin/television-nextjs:latest
    volumes:
      - .:/application
    entrypoint: ["npx", "next", "dev"]
  haproxy:
    image: frankinaustin/television-haproxy:latest
    ports:
      - "80:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  apache:
    image: httpd:2.4
    volumes:
      - ./media/hls:/usr/local/apache2/htdocs/
    environment:
      - TZ=UTC
  postgres:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: television
      POSTGRES_USER: television
      POSTGRES_PASSWORD: television
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql