version: '3.7'  # Updated version to support newer features
services:
  download:
    image: frankinaustin/television-download:latest
    volumes:
      - .:/application
  crt:
    image: frankinaustin/television-crt:latest
    volumes:
      - .:/application
    deploy:
      replicas: 6
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  web:
    image: frankinaustin/television-web:latest
    volumes:
      - .:/application
    entrypoint: ["npx", "next", "dev"]
  haproxy:
    image: frankinaustin/television-haproxy:latest
    ports:
      - "80:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  apache:
    image: httpd:2.4
    volumes:
      - ./workdir/hls:/usr/local/apache2/htdocs/
    environment:
      - TZ=UTC