apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs
        image: frankinaustin/television-nextjs:latest
        imagePullPolicy: Always
        envFrom:  # Use envFrom to load all key-value pairs in the secret as env vars
        - secretRef:
            name: nextjs-env
        volumeMounts:
        - mountPath: /application/
          name: application-data
      volumes:
      - name: application-data
        hostPath:
          path: /home/frank/development/advent-of-code-2023
          type: Directory
