apiVersion: v1
kind: Service
metadata:
  name: nextjs
spec:
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000  # Assuming your Next.js app listens on port 3000 inside the container
  type: ClusterIP  # Default type, accessible only within the cluster
