apiVersion: apps/v1
kind: Deployment
metadata:
  name: crt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crt
  template:
    metadata:
      labels:
        app: crt
    spec:
      securityContext:
        runAsUser: 0  # Run as root
      containers:
      - name: crt
        image: frankinaustin/television-crt:latest
        securityContext:
          privileged: true
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
        volumeMounts:
        - name: application-data
          mountPath: /application
        - name: dev-dri
          mountPath: /dev/dri
      volumes:
      - name: application-data
        hostPath:
          path: /home/frank/development/advent-of-code-2023
          type: Directory
      - name: dev-dri
        hostPath:
          path: /dev/dri