apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler
metadata:
  name: crt-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crt
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  # this really doesn't work that great. pursue having crt scripts self terminate via the k8ts api. 
  # let hpa scale up, and self die
  behavior:   # Behavior field for scaling policies
    scaleUp:
      stabilizationWindowSeconds: 10  # How long to hold off scaling up after the previous scale up
      policies:
      - type: Pods
        value: 1
        periodSeconds: 5
      - type: Percent
        value: 100
        periodSeconds: 5
    scaleDown:
      stabilizationWindowSeconds: 10  # How long to hold off scaling down after the previous scale down
      policies:
      - type: Pods
        value: 1
        periodSeconds: 5
      - type: Percent
        value: 100
        periodSeconds: 5
