apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        env:
        - name: TZ
          value: UTC
        volumeMounts:
        - name: media-hls-data
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: media-hls-data
        hostPath:
          path: /Users/frank/Development/advent-of-code-2023/media/hls
          type: Directory
