import Head from "next/head";
import Image from 'next/image'

import VideoComponent from './VideoComponent'; 

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Televisions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div id="container">
          <VideoComponent />
          <img id="mask" src="/web/televisions_mask.png"></img>
          <Image src="/web/televisions_mask.png" width={1024} height={1024} layout="responsive" alt="a tv repair shop" />
        </div>
      </main>
    </>
  );
}
